agritech/account/urls.py
from django.urls import path, include
from . import views

app_name ='account'
from .views import UserRegistrationView, OTPVerificationView
urlpatterns =[
    path('',views.myAccount),
    path('vendor-detail/<int:vendor_id>/', views.vendor_detail, name='vendor_detail'),

    path('register/', UserRegistrationView.as_view(), name='user_registration'),
    path('verify-otp/', OTPVerificationView.as_view(), name='otp_verification'),
    

    path('login/', views.login, name='login'),
    path('logout/',views.logout, name='logout'),
    path('myAccount/',views.myAccount, name='myAccount'),
    

    path('custdashboard/',views.custdashboard, name='custdashboard'),
    path('vendordashboard/',views.vendordashboard, name='vendordashboard'),
    path('customer_change_password/', views.customer_change_password, name='customer_change_password'),
    path('vendor_change_password/', views.vendor_change_password, name='vendor_change_password'),

    
    path('forgot_password/', views.forgot_password, name='forgot_password'),
    path('reset_password_validate/<uidb64>/<token>/', views.reset_password_validate, name='reset_password_validate'),
    path('reset_password/', views.reset_password, name='reset_password'),
    
    path('vendor/', include('vendor.urls')),
    path('customer/', include('customers.urls')),
    path('order/', include('orders.urls')),

]

agritech/agritech/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views 
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('ecom/',include('ecom.urls')),
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
    path('faq/', views.faq, name='faq'),
    path('agri-support/', views.agro_sup, name='blog'),
    path('contact/', views.contact, name='contact'),
    
    path('account/',include('account.urls')),
    # ORDERS
    path('orders/', include('orders.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

agritech/customers/urls.py
from django.urls import path
from account import views as AccountViews
from . import views


urlpatterns = [
    path('', AccountViews.custdashboard, name='customer'),
    path('profile/', views.cprofile, name='cprofile'),
    path('my_orders/', views.my_orders, name='customer_my_orders'),
    path('customer_order_detail/<int:order_number>/', views.order_detail, name='customer_order_detail'),
    path('my_investment/<int:customer_id>/projects/', views.my_investment, name='my_investment'),
    path('farm_status/<int:id>/', views.cfarm_status, name='cfarm_status'),
]

agritech/ecom/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static
 
app_name ='ecom'

urlpatterns =[
    path('' , views.shop_view,name='shop'),
    path('categories/<int:id>/', views.category_view, name='category-view'),
    path('<int:id>/', views.prod_view, name='product'),
     # ADD TO CART
    path('add_to_cart/<int:project_id>/', views.add_to_cart, name='add_to_cart'),
    # DECREASE CART
    path('decrease_cart/<int:project_id>/', views.decrease_cart, name='decrease_cart'),
    # DELETE CART ITEM
    path('delete_cart/<int:cart_id>/', views.delete_cart, name='delete_cart'),
    path('cart/', views.cart_view,name='cart'),
    
    path('checkout/', views.checkout_view,name='checkout')
   
]

agritech/templates/base2.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

    <head>
        <meta charset="utf-8" />
        <title> AgriTech</title>
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <meta content="Dashboard" name="description" />
        <meta content="MyraStudio" name="author" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        
        <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
        <script src="{% static 'ecom/js/custom.js' %}"></script>
        <script src="https://maps.googleapis.com/maps/api/js?key={{GOOGLE_API_KEY}}&libraries=places&callback=initAutoComplete" async defer></script>
        <!-- App favicon -->
        <link rel="shortcut icon" href="{% static 'ecom/img/favicon.png' %}" type="image/x-icon" />
        <!-- Plugins css -->
        <link href="{% static 'ecom/plugins/datatables/dataTables.bootstrap4.css' %}" rel="stylesheet" type="text/css" />
        <link href="{% static 'ecom/plugins/datatables/responsive.bootstrap4.css' %}" rel="stylesheet" type="text/css" />
        <link href="{% static 'ecom/plugins/datatables/buttons.bootstrap4.css' %}" rel="stylesheet" type="text/css" />
        <link href="{% static 'ecom/plugins/datatables/select.bootstrap4.css' %}" rel="stylesheet" type="text/css" />
        <link href="{% static 'ecom/plugins/dropify/dropify.min.css' %}" rel="stylesheet" type="text/css" />
        
        
        <!-- App css -->
        <link href="{% static 'ecom/assets/css/bootstrap.min.css' %}" rel="stylesheet" type="text/css" />
        <link href="{% static 'ecom/assets/css/icons.min.css' %}" rel="stylesheet" type="text/css" />
        <link href="{% static 'ecom/assets/css/theme.min.css' %}" rel="stylesheet" type="text/css" />
        
        <!-- Sweet Alerts css -->
        <link href="{% static 'ecom/plugins/sweetalert2/sweetalert2.min.css" rel="stylesheet'%}" type="text/css" />

        
    </head>
    
    <body>

        <!-- Begin page -->
        <div id="layout-wrapper" >
            <div class="header-border" ></div>
            <header id="page-topbar">
                <div class="navbar-header">

                    <div class="d-flex align-items-left">
                        <button type="button" class="btn btn-sm mr-2 d-lg-none px-3 font-size-16 header-item waves-effect"
                            id="vertical-menu-btn">
                            <i class="fa fa-fw fa-bars"></i>
                        </button>
                        <div class="dropdown d-none d-sm-inline-block">
                            <a href="{% url 'index' %}">
                            <button type="button" class="btn header-item waves-effect">
                                Home
                            </button>
                            </a>
                            
                        </div>
                        <div class="dropdown d-none d-sm-inline-block">
                            <a href="{% url 'about' %}">
                            <button type="button" class="btn header-item waves-effect">
                                About
                            </button>
                            </a>
                            
                        </div>
                        <div class="dropdown d-none d-sm-inline-block">
                            <a href="{% url 'ecom:shop' %}">
                            <button type="button" class="btn header-item waves-effect">
                                Market
                            </button>
                            </a>
                            
                        </div>
                        <div class="dropdown d-none d-sm-inline-block">
                            <a href="{% url 'contact' %}">
                            <button type="button" class="btn header-item waves-effect">
                                Contact
                            </button>
                            </a>
                            
                        </div>
    
                    </div>
                    <div class="d-flex align-items-center">
                        <div class="dropdown d-inline-block ml-2">
                            <button type="button" class="btn header-item waves-effect"
                                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <a href="{% url 'account:myAccount' %}">
                                    {% if user.userprofile.profile_picture %}
                                    <img class="rounded-circle header-profile-user" src="{{ user.userprofile.profile_picture.url }}"
                                    alt="PP"></a>
                                    {% else %}
                                    <img class="rounded-circle header-profile-user" src="{% static 'ecom/img/icons/user.png' %}"
                                    alt="PP"></a>
                                    {% endif %}
                                <span class="d-none d-sm-inline-block ml-1">{{user.userprofile.full_name}}</span>
                                <i class="mdi mdi-chevron-down d-none d-sm-inline-block"></i>
                            </button>
                            <div class="dropdown-menu dropdown-menu-right">
                                {% if user.get_role == 'Vendor' %}
                                <a class="dropdown-item d-flex align-items-center justify-content-between"
                                    href="{% url 'account:vprofile' %}">
                                    <span>Profile</span>
                                </a>
                                {% else %}
                                <a class="dropdown-item d-flex align-items-center justify-content-between"
                                    
                                href="{% url 'account:cprofile' %}">
                                <span>Profile</span>
                                
                                </a>
                                {% endif %}
                                {% if user.get_role == 'Vendor' %}
                                <a class="dropdown-item d-flex align-items-center justify-content-between"
                                    href="{% url 'account:vendor_change_password' %}">
                                    Change Password
                                </a>
                                {% else %}
                                <a class="dropdown-item d-flex align-items-center justify-content-between"
                                    href="{% url 'account:customer_change_password' %}">
                                    Change Password
                                </a>
                                {% endif %}
                                <a class="dropdown-item d-flex align-items-center justify-content-between"
                                    href="{% url 'account:logout' %}">
                                    <span>Log Out</span>
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
            </header>
        {% if user.get_role == 'Vendor' %}
            {% include "includes/v_sidebar.html" %}
        {% else %}
            {% include "includes/c_sidebar.html" %}
        {% endif %}  
            <!-- ============================================================== -->
            <!-- Start right Content here -->
            <!-- ============================================================== -->
            <div class="main-content">

                <div class="page-content">
                    <div class="container-fluid">

                        
                        {% block dashb %}
                        
                        {% endblock dashb %}

                        
                <!-- End Page-content -->

                <footer class="footer">
                    <div class="container-fluid">
                        <div class="row">
                            <div class="col-sm-6">
                                2023 © AgriTech
                            </div>
                            <div class="col-sm-6">
                                <div class="text-sm-right d-none d-sm-block">
                                    Design & Developed by Janki Solutions
                                </div>
                            </div>
                        </div>
                    </div>
                </footer>

            </div>
            <!-- end main content-->

        </div>
        <!-- END layout-wrapper -->

        <!-- Overlay-->
        <div class="menu-overlay"></div>


        <!-- jQuery  -->
        <script src="{% static 'ecom/assets/js/jquery.min.js' %}"></script>
        <script src="{% static 'ecom/assets/js/bootstrap.bundle.min.js' %}"></script>
        <script src="{% static 'ecom/assets/js/metismenu.min.js' %}"></script>
        <script src="{% static 'ecom/assets/js/waves.js' %}"></script>
        <script src="{% static 'ecom/assets/js/simplebar.min.js' %}"></script>


        <!-- Sparkline Js-->
        <script src="{% static 'ecom/plugins/jquery-sparkline/jquery.sparkline.min.js' %}"></script> 

        <!-- Chart Js-->
         <script src="{% static 'ecom/plugins/jquery-knob/jquery.knob.min.js' %}"></script> 

        <!-- Chart Custom Js-->
        <script src="{% static 'ecom/assets/pages/knob-chart-demo.js' %}"></script>


        <!-- Morris Js-->
         <script src="{% static 'ecom/plugins/morris-js/morris.min.js' %}"></script> 

        <!-- Raphael Js-->
         <script src="{% static 'ecom/plugins/raphael/raphael.min.js' %}"></script> 

        <!-- Custom Js -->
        <script src="{% static 'ecom/assets/pages/dashboard-demo.js' %}"></script>

        <!-- App js -->
        <script src="{% static 'ecom/assets/js/theme.js' %}"></script>
        <!-- third party js -->
        <script src="{% static 'ecom/plugins/datatables/jquery.dataTables.min.js' %}"></script>
        <script src="{% static 'ecom/plugins/datatables/dataTables.bootstrap4.js' %}"></script>
        <script src="{% static 'ecom/plugins/datatables/dataTables.responsive.min.js' %}"></script>
        <script src="{% static 'ecom/plugins/datatables/responsive.bootstrap4.min.js' %}"></script>
        <script src="{% static 'ecom/plugins/datatables/dataTables.buttons.min.js' %}"></script>
        <script src="{% static 'ecom/plugins/datatables/buttons.bootstrap4.min.js' %}"></script>
        <script src="{% static 'ecom/plugins/datatables/buttons.html5.min.js' %}"></script>
        <script src="{% static 'ecom/plugins/datatables/buttons.flash.min.js' %}"></script>
        <script src="{% static 'ecom/plugins/datatables/buttons.print.min.js' %}"></script>
        <script src="{% static 'ecom/plugins/datatables/dataTables.keyTable.min.js' %}"></script>
        <script src="{% static 'ecom/plugins/datatables/dataTables.select.min.js' %}"></script>
        <script src="{% static 'ecom/plugins/datatables/pdfmake.min.js' %}"></script>
        <script src="{% static 'ecom/plugins/datatables/vfs_fonts.js' %}"></script>
        <!-- third party js ends -->

        <!-- Datatables init -->
        <script src="{% static 'ecom/assets/pages/datatables-demo.js' %}"></script>
        <script src="{% static 'ecom/plugins/dropify/dropify.min.js' %}"></script>
        <script src="{% static 'ecom/assets/pages/fileuploads-demo.js' %}"></script>

        <!-- Sweet Alerts Js-->
        <script src="{% static 'ecom/plugins/sweetalert2/sweetalert2.min.js' %}"></script>
        

        <!-- Sweet Alerts Js-->
        <script src="{% static 'ecom/assets/pages/sweet-alert-demo.js' %}"></script>

    </body>

</html>