agritech/account/urls.py
from django.urls import path, include
from . import views

app_name ='account'
from .views import UserRegistrationView, OTPVerificationView
urlpatterns =[
    path('',views.myAccount),
    path('vendor-detail/<int:vendor_id>/', views.vendor_detail, name='vendor_detail'),

    path('register/', UserRegistrationView.as_view(), name='user_registration'),
    path('verify-otp/', OTPVerificationView.as_view(), name='otp_verification'),
    

    path('login/', views.login, name='login'),
    path('logout/',views.logout, name='logout'),
    path('myAccount/',views.myAccount, name='myAccount'),
    

    path('custdashboard/',views.custdashboard, name='custdashboard'),
    path('vendordashboard/',views.vendordashboard, name='vendordashboard'),
    path('customer_change_password/', views.customer_change_password, name='customer_change_password'),
    path('vendor_change_password/', views.vendor_change_password, name='vendor_change_password'),

    
    path('forgot_password/', views.forgot_password, name='forgot_password'),
    path('reset_password_validate/<uidb64>/<token>/', views.reset_password_validate, name='reset_password_validate'),
    path('reset_password/', views.reset_password, name='reset_password'),
    
    path('vendor/', include('vendor.urls')),
    path('customer/', include('customers.urls')),
    path('order/', include('orders.urls')),

]

agritech/agritech/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views 
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('ecom/',include('ecom.urls')),
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
    path('faq/', views.faq, name='faq'),
    path('agri-support/', views.agro_sup, name='blog'),
    path('contact/', views.contact, name='contact'),
    
    path('account/',include('account.urls')),
    # ORDERS
    path('orders/', include('orders.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

agritech/customers/urls.py
from django.urls import path
from account import views as AccountViews
from . import views


urlpatterns = [
    path('', AccountViews.custdashboard, name='customer'),
    path('profile/', views.cprofile, name='cprofile'),
    path('my_orders/', views.my_orders, name='customer_my_orders'),
    path('customer_order_detail/<int:order_number>/', views.order_detail, name='customer_order_detail'),
    path('my_investment/<int:customer_id>/projects/', views.my_investment, name='my_investment'),
    path('farm_status/<int:id>/', views.cfarm_status, name='cfarm_status'),
]

agritech/ecom/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static
 
app_name ='ecom'

urlpatterns =[
    path('' , views.shop_view,name='shop'),
    path('categories/<int:id>/', views.category_view, name='category-view'),
    path('<int:id>/', views.prod_view, name='product'),
     # ADD TO CART
    path('add_to_cart/<int:project_id>/', views.add_to_cart, name='add_to_cart'),
    # DECREASE CART
    path('decrease_cart/<int:project_id>/', views.decrease_cart, name='decrease_cart'),
    # DELETE CART ITEM
    path('delete_cart/<int:cart_id>/', views.delete_cart, name='delete_cart'),
    path('cart/', views.cart_view,name='cart'),
    
    path('checkout/', views.checkout_view,name='checkout')
   
]

agritech/customers/models.py
from django.db import models

# Create your models here.

agritech/customers/views.py
from django.shortcuts import get_object_or_404, redirect, render
from django.contrib.auth.decorators import login_required
from account.forms import UserProfileForm
from account.models import UserProfile
from django.contrib import messages
from orders.models import Order, FarmOrder
from account.models import User
from ecom.models import Project
import json
from ecom.models import ProjectStatus
from django.db.models import Sum

@login_required(login_url='login')
def cprofile(request):
    profile = get_object_or_404(UserProfile, user=request.user)
    
    if request.method == 'POST':
        
        print(request.POST)
        profile_form = UserProfileForm(request.POST, request.FILES, instance=profile)
        
        if profile_form.is_valid() :
            profile_form.save()
            
            messages.success(request, 'Profile updated')
            return redirect('account:cprofile')
        else:
            print(profile_form.errors)
            
    else:
       
        profile_form = UserProfileForm(instance=profile)
        

    context = {
        'profile_form': profile_form,
        'profile': profile,
    }
    return render(request, 'customers/cprofile.html', context)


def my_orders(request):
    orders = Order.objects.filter(user=request.user, is_ordered=True).order_by('-created_at')

    context = {
        'orders': orders
    }
    return render(request, 'customers/my_orders.html', context)





def order_detail(request, order_number):
    try:
        order = Order.objects.get(order_number=order_number, is_ordered=True)
        ordered_product = FarmOrder.objects.filter(order=order)
        subtotal = 0
        for item in ordered_product:
            subtotal += (item.price * item.quantity)
        tax_data = json.loads(order.tax_data) if order.tax_data else {}
        context = {
            'order': order,
            'ordered_product': ordered_product,
            'subtotal': subtotal,
            'tax_data': tax_data,
        }
    except json.JSONDecodeError as e:
        print(f"Error decoding tax_data: {str(e)}")
    
    return render(request, 'customers/order_detail.html', context)

    
def my_investment(request, customer_id):
    # Assuming customer_id is the ID of the customer user

    # Retrieve the customer user object
    customer = User.objects.get(id=customer_id, role=User.CUSTOMER)

    # Retrieve the ordered projects by the customer
    ordered_projects = Project.objects.filter(farmorder__user=customer).distinct()

    # Search functionality
    search_query = request.GET.get('search', '')  # the search query from the GET parameters
    if search_query:
        ordered_projects = ordered_projects.filter(project_title__icontains=search_query)

    # Create a dictionary to store project details, quantity, and price paid
    project_details = {}

    # Iterate over the ordered projects
    for project in ordered_projects:
        # Retrieve the FarmOrder objects for the project and customer
        farm_orders = FarmOrder.objects.filter(user=customer, project=project)

        # Initialize variables to store the total quantity and price paid for the project
        total_quantity = 0
        # total_price_paid = 0

        # Iterate over the FarmOrder objects
        for farm_order in farm_orders:
            # Get the quantity and price paid for each FarmOrder
            quantity_ordered = farm_order.quantity
            # price_paid = farm_order.amount

            # Increment the total quantity and price paid
            total_quantity += quantity_ordered
            # total_price_paid += price_paid

        # Store the project details, total quantity, and total price paid in the dictionary
        project_details[project] = {
            'quantity_ordered': total_quantity,
            # 'price_paid': total_price_paid,
        }

    # Pass the project details dictionary to the template
    return render(request, 'customers/my_investment.html', {'project_details': project_details})

@login_required(login_url='account:login')
def cfarm_status(request, id):
    project = get_object_or_404(Project, id=id)
    
    # Retrieve the status messages for the specific project ID
    status_messages = ProjectStatus.objects.filter(project_id=id).order_by('created_at')
    
    # Calculate the invested amount for the current user and project
    invested_amount = FarmOrder.objects.filter(project=project, user=request.user).aggregate(Sum('amount'))['amount__sum'] or 0
    
    # Calculate the return amount for the current user and project
    return_amount = FarmOrder.objects.filter(project=project, user=request.user).aggregate(Sum('return_amount'))['return_amount__sum'] or 0
    
    context = {
        'project': [project],
        'status_messages': status_messages,
        'invested_amount': invested_amount,
        'return_amount': return_amount,
    }
    
    return render(request, 'customers/cfarm_status.html', context)

agritech/customers/templates/customers/cfarm_status.html
{% extends 'base2.html' %}
{% load static %}
{% load humanize %}
{% block dashb %}
{% include 'includes/alerts.html' %}
{% for proj in project %}
<!-- start page title -->
<div class="row">
    <div class="col-8">
        <div class="page-title-box d-flex align-items-center justify-content-between">
            <h2 class="mb-0 font-size-38 mt-2">{{proj.project_title}}
                    {% if proj.is_completed %}
                        <span class="badge badge-success rounded-pill" >Completed</span>
                     {% elif proj.is_soldout%}
                        <span class="badge badge-danger rounded-pill" > Soldout</span>
                     {% else %}
                        <span class="badge badge-success rounded-pill" >Active</span>
                     {% endif %}
            </h2>
            <span style="float:right;">
              Farmer:<b><a href="{% url 'account:vendor_detail' vendor_id=proj.vendor.id %}">{{ proj.vendor.user.user_profile.first_name }} {{ proj.vendor.user.user_profile.last_name }}</a></b>
              <img src="{% static 'ecom/img/verified.png' %}">
              </span>
        </div>
    </div>
</div>
<!-- end page title -->

<div style="display: flex;">
  <div>
    <div class="card">
      <img class="card-img-top img-fluid" src="{{ proj.farm_image.url }}" alt="Card image cap" style="width:60rem ; height:50rem; object-fit: cover;">
      <div class="card-body">
        <p class="card-text">
          <strong>Invested Amount:</strong>  
          <a>रु‎ {{ invested_amount }} </a>
          <br>
        </p> 
        <p>
          {% if proj.is_completed %}
          <strong>Profit Gained:</strong>
          {% else %}
          <strong>Expected Profit:</strong>
          {% endif %}
          <span class="greenish">
            <a>रु‎ {{ return_amount }} </a>
          </span><br>
          <p>
          <strong>Active Since:</strong>
            <span class="greenish">
                <a>{{ proj.days_since_created }} Days</a>
            </span><br>
          </P>
        </p>
      </div>
    </div>
      
      <div class="card" style="max-height: 350px;">
        <div class="card-body">
          <ul class="nav nav-tabs nav-justified mb-2" style="max-height: 30px;">
            <li class="nav-item">
              <a href="#home1" data-toggle="tab" aria-expanded="false" class="nav-link">
                <i class="mdi mdi-home-variant d-lg-none d-block"></i>
                <span class="d-none d-lg-block">Description</span>
              </a>
            </li>
            <li class="nav-item">
              <a href="#profile1" data-toggle="tab" aria-expanded="true" class="nav-link active">
                <i class="mdi mdi-account-circle d-lg-none d-block"></i>
                <span class="d-none d-lg-block">Location</span>
              </a>
            </li>
          </ul>
      
          <div class="tab-content" style="max-height: 300px;">
            <div class="tab-pane" id="home1">
              <p>{{proj.project_description}}</p>
            </div>
            <div class="tab-pane show active" id="profile1">
              <p><strong>Location:</strong> <span class="greenish">{{ proj.address }}</span></p>
              <div id="map" style="height: 250px;"></div>
            </div>
          </div>
        </div> <!-- end card-body-->
      </div> <!-- end card-->
      
  </div>
  <div >
    <div class="col" style="margin-left:10px;">
      <div class="card">
        <div class="card-body col-xl-22">
          <h3>Farm Details</h3>
          <hr>
          <p class="card-text">
            <strong>Duration:</strong>
            <span>
                <a>{{ proj.duration_in_months }} months</a>
            </span><br>
            <strong>Posted Date:</strong>
            <span>
                <a>{{ proj.created_at|date:"M. d, Y" }}</a>
            </span><br>                                                                                      
            <strong>Return Date:</strong>
            <span>
                <a>{{ proj.return_date }}</a>
            </span><br>
            <hr>
            <strong>Total Cost:</strong>
              <span>
                  <a>रु‎ {{ proj.total_cost|floatformat:2|intcomma }}</a>
              </span><br>
              <strong>Farmer Investment:</strong>
              <span>
                  <a>रु‎{{ proj.fund_invested|floatformat:2|intcomma }}</a>
              </span><br>
              <strong>Demand:</strong>
              <span>
                  <a>रु‎{{ proj.demand|floatformat:2|intcomma}}</a>
              </span><br>
              <hr>
              <strong><a href="{% url 'ecom:product' id=proj.id %}">Available Shares:</a></strong> 
              <span>
                  <b>{{ proj.total_no_shares }}</b>
              </span>
              
            </p>
            
        </div>
      </div>
      <div class="card">
        <div class="card-body">
            <h5 class="card-title">FARM STATUS</h5>  
            {% for status in status_messages %}
<div class="card mb-0">
  <div class="card-header" id="heading{{ forloop.counter }}">
    <h5 class="m-0 font-size-15">
      <a class="collapsed d-block pt-2 pb-2 text-dark" data-toggle="collapse" href="#collapse{{ forloop.counter }}" aria-expanded="false" aria-controls="collapse{{ forloop.counter }}">
        {{ status.title }} <span class="float-right"><i class="mdi mdi-chevron-down accordion-arrow"></i></span>
      </a>
    </h5>
  </div>
  <div id="collapse{{ forloop.counter }}" class="collapse" aria-labelledby="heading{{ forloop.counter }}">
    <div class="card-body">
      {{ status.status }}
    </div>
  </div>
</div>
<!-- end card-->
{% empty %}
<div class="card mb-0">
  <div class="card-header">
    <h5 class="m-0 font-size-15">
      No status messages found.
    </h5>
  </div>
</div>
{% endfor %}
        </div>
    </div>
    </div>
  </div>
</div>
{% for proj in project  %}


<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="https://maps.googleapis.com/maps/api/js?key={{GOOGLE_API_KEY}}&libraries=places"></script>
<script src="{% static 'ecom/js/location_picker.js' %}"></script>
<script>
    var map;
    var marker;

    function initMap() {
        var initialLat = parseFloat({{ proj.latitude }}) || 27.706112;
        var initialLng = parseFloat({{ proj.longitude }}) || 85.345665;

        map = new google.maps.Map(document.getElementById('map'), {
            zoom: 12,
            center: { lat: initialLat, lng: initialLng }
        });

        marker = new google.maps.Marker({
            map: map,
            position: { lat: initialLat, lng: initialLng }
        });
    }

    google.maps.event.addDomListener(window, 'load', initMap);
</script>
{% endfor %}
{% endfor %}
{% endblock %}

agritech/customers/templates/customers/cprofile.html
{% extends 'base2.html' %}
{% load static %}
{% block dashb %}

{% include 'includes/alerts.html' %}
<!-- Main Section Start -->

<div class="col-xl-10">
	<div class="card">
		<div class="card-body">
			<h2 class=" text-center">Manage Profile</h2>
			{% if not user.is_verified %}
			<h5 style="text-align:center; color:red;">Please update your profile to verify your account.</h5>
			{% endif %}
			<br>
			<form action="{% url 'account:cprofile' %}" method="POST" enctype="multipart/form-data">
				{% csrf_token %}
				
				{% comment %} profile picture code  {% endcomment %}
				<div class="text-center">
					{% if profile.profile_picture %}
						<img  src="{{ profile.profile_picture.url }}" alt="Profile Picture"  style="max-height: 280px; max-width: 200px; border-radius: 5%;">
					{% else %}
						<img src="{% static 'ecom/img/back2.jpg' %}" alt="Profile Picture" style="max-height: 280px; max-width: 200px; border-radius: 5%;"
						>
					{% endif %}
				</div>
				<div class="text-center">
					<label><b>Update Profile Picture</b></label>
					<div class="col-xl-12">
						<label for="profile-picture" class="btn btn-success btn-rounded waves-effect waves-light" style="background-color: #09c199; color: white;">
							<i class="fas fa-paperclip"></i> Attach File
						  </label>
						  <input type="file" class="d-none" name="profile_picture" id="profile-picture">
						  
					</div>
					<label class="labels">{{ profile_form.profile_picture.errors }}</label>
				</div>
				
				<label> Choose Documents </label>
				<div class="col-xl-12">
					<div class="mb-4">
						<p>
							<a class="btn btn-outline-success btn-rounded waves-effect waves-light" data-toggle="collapse" href="#collapseP" aria-expanded="false" aria-controls="collapseExample" style="margin-left:-10px;">
								Passport
							</a>
							<a class="btn btn-outline-success btn-rounded waves-effect waves-light ml-10" data-toggle="collapse" href="#collapseN" aria-expanded="false" aria-controls="collapseExample" style="margin-left:20px;">
								Citizenship
							</a>
						</p>
						<div class="collapse" id="collapseP">
							<div class="card card-body">
								<div style="display: flex; align-items: center;">
									<div class="text-left" style="margin-right: 10px;">
										{% if profile.passport_photo %}
											<img src="{{ profile.passport_photo.url }}" alt="e" class="avatar-md rounded-circle img-thumbnail">
										{% else %}
											<img src="{% static 'images/default-passport.png' %}" alt="" class="avatar-md rounded-circle img-thumbnail">
										{% endif %}
									</div>
									<div>
										<label><b>Update Passport Photo</b></label>
										<div>
											<input type="file" class="dropify" name="passport_photo" id="passport-photo" style="background-color: #00a474; color: white;">
										</div>
									</div>
								</div>
								<label class="labels">{{ profile_form.passport_photo.errors }}</label>
							</div>
						</div>
						
						
						<div class="collapse" id="collapseN">
							<div class="card">
								<div style="display: flex; align-items: center;">
									<div class="text-left" style="margin-right: 10px;">
										{% if profile.citizenship_front %}
											<img src="{{ profile.citizenship_front.url }}" alt="" class="avatar-md rounded-circle img-thumbnail">
										{% else %}
											<img src="{% static 'images/default-citizenship.png' %}" alt="" class="avatar-md rounded-circle img-thumbnail">
										{% endif %}
									</div>
									<div>
										<label><b> Citizenship Front </b></label>
										<div class="col-xl-12">
											<input type="file" class="dropify" data-width="100" name="citizenship_front" id="citizenship-front" style="background-color: #00a474; color: white;">
										</div>
									</div>
								</div>
								<label class="labels">{{ profile_form.citizenship_front.errors }}</label>
							</div>
							<br>
							<div class="card card-body">
								<div style="display: flex; align-items: center;">
									<div class="text-left" style="margin-right: 10px;">
										{% if profile.citizenship_back %}
										<img src="{{ profile.citizenship_back.url }}" alt="" class="avatar-md rounded-circle img-thumbnail">
										{% else %}
											<img src="{% static 'images/default-citizenship.png' %}" alt="" class="avatar-md rounded-circle img-thumbnail">
										{% endif %}
									</div>
									<div>
										<label><b> Citizenship Back </b></label>
										<div class="col-xl-12">
											<input type="file" class="dropify" name="citizenship_back" id="citizenship-back">
										</div>
									</div>
								</div>
								<label class="labels">{{ profile_form.citizenship_back.errors }}</label>
							</div>
						</div>
					</div> <!-- end .mb-4 -->
				</div> <!-- end col -->
				<div class="row">
					<div class="form-group col-xl-6">
						<label>First Name</label>
						{{ profile_form.first_name }}
					</div>

					<div class="form-group col-xl-6">
						<label>Last Name</label>
						{{ profile_form.last_name }}
					</div>
			</div>
				<div class="form-group">
          <label><b>Address *</b></label>
          {{profile_form.address}}
          <small class="text-muted float-right" style="color: darkblue"
            >powered by Google</small
          >
        </div>
        <div class="form-group">
          <label><b>Email *</b></label>
          {{ profile_form.email }}
        </div>
        
        <div class="form-group">
          <label><b>Gender</b></label>
          {{ profile_form.gender }}
        </div>
        

        <div class="container">
			<div class="row">
			  <div class="col-6">
				<div class="form-group">
				  <label><b>Country *</b></label>
				  {{ profile_form.country }}
				</div>
			  </div>
			  <div class="col-6">
				<div class="form-group">
				  <label><b>State *</b></label>
				  {{ profile_form.state }}
				</div>
			  </div>
			  <div class="col-6">
				<div class="form-group">
				  <label><b>City *</b></label>
				  {{ profile_form.city }}
				</div>
			  </div>
			  <div class="col-6">
				<div class="form-group">
				  <label><b>Pin Code *</b></label>
				  {{ profile_form.pin_code }}
				</div>
			  </div>
			</div>
		  </div>
				<button type="submit" class="btn btn-primary btn-rounded waves-effect waves-light">Submit</button>
			</form>

		</div> <!-- end card-body-->
	</div> <!-- end card-->
</div>

<!-- Main Section End -->
{% endblock dashb %}

agritech/customers/templates/customers/my_investment.html
{% extends 'base2.html' %}
{% load static %}

{% block dashb %}
{% include 'includes/alerts.html' %}
<!-- start page title -->
<div class="row">
    <div class="col-12">
        <div class="page-title-box d-flex align-items-center justify-content-between">
            <h4 class="mb-0 font-size-18">My Investments</h4>
        </div>
    </div>
</div>
<!-- end page title -->
<form class="p-3" method="GET">
    <div class="form-group m-0">
        <div class="input-group">
            <input type="text" name="search" value="{{ search_query }}" class="form-control" placeholder="Search by project title"
                aria-label="Recipient's username">
            <div class="input-group-append">
                <button class="btn btn-primary" type="submit"><i
                        class="mdi mdi-magnify"></i></button>
            </div>
        </div>
    </div>
</form>
<br>
<div class="row">
{% for project, details in project_details.items %}
    <div class="col-md-6 col-xl-3">
        <div class="card">
            <div class="card-body">
                <h5 class="card-title"><a href="{% url 'account:cfarm_status' project.id %}">{{ project.project_title }}</a>
                    {% if project.is_completed %}
                        <span class="badge badge-success rounded-pill" >Completed</span>
                     {% elif project.is_soldout%}
                        <span class="badge badge-danger rounded-pill" > Soldout</span>
                     {% else %}
                        <span class="badge badge-success rounded-pill" >Active</span>
                      {% endif %}</h5>
                <h6 class="card-subtitle text-muted">{{project.project_type}}</h6>
            </div>
            <img class="img-fluid" src="{{ project.farm_image.url }}" alt="Farm Image" style="width: 400px; height: 200px; object-fit: cover;">
            <div class="card-body">
                <h6 style="display: flex; align-items: center;">
                    Shares owned: {{ details.quantity_ordered }}
                    <a href="{% url 'account:cfarm_status' project.id %}">
                      <button type="button" class="btn btn-danger btn-sm waves-effect waves-light" 
                      style="margin-left: 50px; background-color: #E8A430;">View Details</button>
                    </a>
                </h6>
                  
            </div>
        </div>

    </div><!-- end col -->
    {% endfor %}
</div>

{% endblock %}

agritech/customers/templates/customers/my_orders.html
{% extends 'base2.html' %}
{% load static %}

{% block dashb %}
{% include 'includes/alerts.html' %}
<!-- start page title -->
<div class="row">
    <div class="col-12">
        <div class="page-title-box d-flex align-items-center justify-content-between">
            <h4 class="mb-0 font-size-18">My Orders</h4>
        </div>
    </div>
</div>
<!-- end page title -->
<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-body">

                <h4 class="card-title">Orders</h4>
                <table id="datatable-buttons" class="table table-striped dt-responsive nowrap">
                    <thead>
                        <tr>
                            <th scope="col">Order ID</th>
                            <th scope="col">Name</th>
                            <th scope="col">Total</th>
                            <th scope="col">Status</th>
                            <th scope="col">Date</th>
                            <th scope="col"></th>
                        </tr>
                    </thead>
                
                
                    <tbody>
                        {% for order in orders %}
                          <tr>
                            <td>{{ order.order_number }}</td>
                            <td>{{ order.name }}</td>
                            <td>NRS. {{ order.total }}</td>
                            <td>{{ order.status }}</td>
                            <td>{{ order.created_at }}</td>
                            <td><a href="{% url 'account:customer_order_detail' order.order_number %}" class="btn btn rounded-lg" style="background-color:#2B3D51;color:white;">Details</a></td>

                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
                
            </div> <!-- end card body-->
        </div> <!-- end card -->
    </div><!-- end col-->
</div>
<!-- end row-->
{% endblock %}

agritech/customers/templates/customers/order_detail.html
{% extends 'base2.html' %}
{% load static %}

{% block dashb %}
{% include 'includes/alerts.html' %}
<!-- start page title -->
<div class="row">
    <div class="col-12">
        <div class="page-title-box d-flex align-items-center justify-content-between">
            <h4 class="mb-0 font-size-18">Order Detail</h4>
        </div>
    </div>
</div>
<!-- end page title -->
<div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="card-body">
                <div class="clearfix">
                    <div class="float-left">
                        
                    </div>
                    <div class="float-right">
                        <h4 class="m-0 d-print-none">Invoice</h4>
                    </div>
                </div>


                <div class="row mt-4">
                    <div class="col-6">
                        <h6 class="font-weight-bold">TO:</h6>

                        <address class="line-h-24">
                            <b>{{ order.name }}</b><br>
                            {{ order.address }}<br>
                            {{ order.email }}<br>
                             {{ order.phone }}
                        </address>
                    </div><!-- end col -->
                    <div class="col-6">
                        <div class="mt-3 float-right">
                            <p class="mb-2"><strong>Order Date: </strong> {{ order.created_at }}</p>
                            <p class="mb-2"><strong>Order Status: </strong> <span class="badge badge-soft-success">Paid</span></p>
                            <p class="m-b-10"><strong>Order ID: </strong>{{ order.order_number }}</p>
                        </div>
                    </div><!-- end col -->
                </div>
                <!-- end row -->

                <div class="row">
                    <div class="col-md-12">
                        <div class="table-responsive">
                            <table class="table mt-4">
                                <thead>
                                <tr>
                                    <th>Item</th>
                                    <th>No of Share</th>
                                    <th>Share Value</th>
                                </tr></thead>
                                <tbody>
                                    {% for item in ordered_product %}
                                <tr>
                                    
                                    <td>
                                        <img src="{{ item.project.farm_image.url }}" width="60" alt="Product Image">{{ item.project }}
                                    </td>
                                    <td>{{ item.quantity }}</td>
                                    <td>रु‎{{ item.project.value_of_share}}</td>
                                </tr>
                                {% endfor %}

                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-6">
                        <div class="clearfix pt-5">
                            <h6 class="text-muted"></h6>

                            <small>
                               
                            </small>
                        </div>

                    </div>
                    <div class="col-6">
                        <div class="float-right">
                            <p><b>Sub-total:</b> रु‎ {{ subtotal }}</p>
                            {% for key, value in tax_data.items %}
                            {% for i, j in value.items %}
                            <li style="list-style-type: none;">
                                <b>{{ key }} <small>({{ i }}%)</small>:</b>
                                    रु‎
                                    <span id="tax-{{ key }}">{{ j }}</span>
                            </li>
                            {% endfor %}
                            {% endfor %}
                            <br>
                            <h3> रु‎ {{ order.total }} NPR</h3>
                        </div>
                        <div class="clearfix"></div>
                    </div>
                </div>

                <div class="d-print-none my-4">
                    <div class="text-right">
                        <a href="javascript:window.print()" class="btn btn-primary waves-effect waves-light"><i class="fa fa-print m-r-5"></i> Print</a>
                    </div>
                </div>
            </div>
        </div> <!-- end card-->
    </div> <!-- end col -->
</div>
<!-- end row-->
{% endblock %}