agritech/account/urls.py
from django.urls import path, include
from . import views

app_name ='account'
from .views import UserRegistrationView, OTPVerificationView
urlpatterns =[
    path('',views.myAccount),
    path('vendor-detail/<int:vendor_id>/', views.vendor_detail, name='vendor_detail'),

    path('register/', UserRegistrationView.as_view(), name='user_registration'),
    path('verify-otp/', OTPVerificationView.as_view(), name='otp_verification'),
    

    path('login/', views.login, name='login'),
    path('logout/',views.logout, name='logout'),
    path('myAccount/',views.myAccount, name='myAccount'),
    

    path('custdashboard/',views.custdashboard, name='custdashboard'),
    path('vendordashboard/',views.vendordashboard, name='vendordashboard'),
    path('customer_change_password/', views.customer_change_password, name='customer_change_password'),
    path('vendor_change_password/', views.vendor_change_password, name='vendor_change_password'),

    
    path('forgot_password/', views.forgot_password, name='forgot_password'),
    path('reset_password_validate/<uidb64>/<token>/', views.reset_password_validate, name='reset_password_validate'),
    path('reset_password/', views.reset_password, name='reset_password'),
    
    path('vendor/', include('vendor.urls')),
    path('customer/', include('customers.urls')),
    path('order/', include('orders.urls')),

]

agritech/agritech/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views 
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('ecom/',include('ecom.urls')),
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
    path('faq/', views.faq, name='faq'),
    path('agri-support/', views.agro_sup, name='blog'),
    path('contact/', views.contact, name='contact'),
    
    path('account/',include('account.urls')),
    # ORDERS
    path('orders/', include('orders.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

agritech/ecom/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static
 
app_name ='ecom'

urlpatterns =[
    path('' , views.shop_view,name='shop'),
    path('categories/<int:id>/', views.category_view, name='category-view'),
    path('<int:id>/', views.prod_view, name='product'),
     # ADD TO CART
    path('add_to_cart/<int:project_id>/', views.add_to_cart, name='add_to_cart'),
    # DECREASE CART
    path('decrease_cart/<int:project_id>/', views.decrease_cart, name='decrease_cart'),
    # DELETE CART ITEM
    path('delete_cart/<int:cart_id>/', views.delete_cart, name='delete_cart'),
    path('cart/', views.cart_view,name='cart'),
    
    path('checkout/', views.checkout_view,name='checkout')
   
]

agritech/ecom/forms.py
from django import forms

from account.validators import allow_only_images_validator
from .models import Category, ExtraImage, Project ,ProjectStatus
from django.utils.translation import gettext_lazy as _
from django.forms import inlineformset_factory
from django.forms import formset_factory


class CategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = ['category_name']



from django import forms
from .models import Project

class ProjectForm(forms.ModelForm):
    project_title = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'form-control'}),
        required=False
    )
    farm_image = forms.ImageField(
        widget=forms.ClearableFileInput(attrs={'class': 'form-control-file'}),
        required=False
    )
    return_date = forms.DateField(
        widget=forms.DateInput(attrs={'class': 'form-control', 'type': 'date'}),
        required=False
    )
    extra_images = forms.ImageField(
        widget=forms.ClearableFileInput(attrs={'class': 'form-control-file', 'multiple': False}),
        required=False
    )
  
    class Meta:
        model = Project
        fields = ['project_title', 'project_type', 'project_description', 'project_documents', 'total_cost', 'farm_image', 'is_available',
                  'value_of_share', 'max_shares_per_user', 'return_date', 'percent_return_after_due_date', 'extra_images',
                  'address', 'latitude', 'longitude']
        exclude = ['is_approved', 'is_completed', 'is_soldout']


    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs.update({'class': 'form-control'})



ExtraImageFormSet = formset_factory(ProjectForm, extra=1, can_delete=True)


class EditProjectForm(forms.ModelForm):
    
    farm_image = forms.ImageField(
        widget=forms.ClearableFileInput(attrs={'class': 'form-control-file'}),
        required=False
    )
    
    extra_images = forms.ImageField(
        widget=forms.ClearableFileInput(attrs={'class': 'form-control-file', 'multiple': False}),
        required=False
    )

    project_document = forms.FileField(required=False)
  
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            if field_name not in ['is_available', 'is_approved', 'is_completed', 'is_soldout']:
                field.widget.attrs.update({'class': 'form-control'})


    class Meta:
        model = Project
        fields = [ 'project_description','farm_image','project_documents',
                    'extra_images']
        exclude = ['is_approved', 'is_completed', 'is_soldout']

agritech/ecom/views.py
from django.forms import ValidationError
from django.shortcuts import render, get_object_or_404,redirect
from django.http.response import JsonResponse
from django.urls import reverse
from account.models import User
from account.views import check_role_customer
from ecom.models import Category,Project
from django.core.paginator import Paginator
from django.contrib.auth.decorators import login_required , user_passes_test
from .models import Cart,UserProfile,UserProfile, User, is_project_approved
from .context_processors import get_cart_counter , get_cart_amounts
from orders.forms import OrderForm
from django.db.models import Count
from django.db.models import F
from django.db.models import Q


def shop_view(request):
    categories = Category.objects.all()
    projects = Project.objects.filter(is_approved=True, is_soldout=False)
    top_projects = Project.objects.filter(is_approved=True, is_soldout=False, is_completed=False).order_by(
        '-percent_return_after_due_date')[:3]
    page = request.GET.get('page')
    search_query = request.GET.get('search_query')
    sort_by = request.GET.get('sort_by')

    if sort_by == 'percent_return':
        projects = projects.order_by('-percent_return_after_due_date')
    elif sort_by == 'duration':
        projects = projects.order_by(F('return_date') - F('created_at'))
    elif sort_by == 'value_of_share':
        projects = projects.order_by('value_of_share')

    if search_query and search_query.strip() != '':
        project_ids = []
        for project in projects:
            if (project.project_title and project.project_title.lower().find(search_query.lower()) != -1) or \
                    (project.address and project.address.lower().find(search_query.lower()) != -1):
                project_ids.append(project.id)

        user_profile_ids = [profile.user.id for profile in UserProfile.objects.filter(
            Q(first_name__icontains=search_query) | Q(
                last_name__icontains=search_query)
        )]

        vendor_ids = [vendor.id for vendor in User.objects.filter(
            Q(id__in=user_profile_ids) & Q(role=User.VENDOR)
        )]

        projects = projects.filter(Q(id__in=project_ids) | Q(vendor_id__in=vendor_ids))


    paginator = Paginator(projects, 8)
    project_page = paginator.get_page(page)

    context = {
        'top_projects': top_projects,
        'categories': categories,
        'project_page': project_page,
        'sort_by': sort_by,
        'projects': projects
    }

    return render(request, 'ecom/shop-grid.html', context)

def category_view(request, id):
    categories = Category.objects.all()
    top_projects = Project.objects.filter(is_approved=True, project_type__id=id).order_by('-percent_return_after_due_date')[:3]
    category_project = Project.objects.filter(project_type__id=id)

    # Retrieve the search query from the request parameters
    search_query = request.GET.get('search_query')

    if search_query and search_query.strip() != '':
        category_project = category_project.filter(
            Q(project_title__icontains=search_query) |
            Q(project_description__icontains=search_query) |
            Q(vendor__userprofile__first_name__icontains=search_query) |
            Q(vendor__userprofile__last_name__icontains=search_query)
        )

    # Adding pagination
    paginator = Paginator(category_project, 8)  # Show 8 projects per page
    page = request.GET.get('page')
    category_project_page = paginator.get_page(page)

    context = {
        'category_project': category_project, 
        'category_project_page':category_project_page,
        'top_projects': top_projects,
        'categories': categories,
    }
    return render(request, 'ecom/category-view.html', context)



@is_project_approved
def prod_view(request, id):
    project = get_object_or_404(Project, id=id)
    
    # Check if the logged-in user is the vendor of the project
    
    top_projects = Project.objects.filter(is_approved=True).order_by('-percent_return_after_due_date')[:3]
    related_projects = Project.objects.filter(project_type=project.project_type).exclude(id=project.id)[:5]
    
    if related_projects.count() < 5:
        additional_projects = Project.objects.exclude(id=project.id).annotate(num_projects=Count('id')).order_by('-num_projects')[:5 - related_projects.count()]
        related_projects = list(related_projects) + list(additional_projects)
    
    if request.user.is_authenticated:
        cart_items = Cart.objects.filter(user=request.user)
    else:
        cart_items = None
    
    context = {
        'project': [project],
        'top_projects': top_projects,
        'related_projects': related_projects,
        'cart_items': cart_items,
    }
    
    return render(request, 'ecom/product-details.html', context)


@user_passes_test(check_role_customer)
def add_to_cart(request, project_id):
    if not request.user.is_authenticated:
        return JsonResponse({'status': 'login_required', 'message': 'Please login to continue'})

    try:
        project = Project.objects.get(id=project_id)
        try:
            chkCart = Cart.objects.get(user=request.user, project=project)
            if chkCart.quantity < project.max_shares_per_user:
                chkCart.quantity += 1
                chkCart.save()
                return JsonResponse({'status': 'Success', 'message': 'Increased the cart quantity', 'cart_counter': get_cart_counter(request), 'qty': chkCart.quantity, 'cart_amount': get_cart_amounts(request)})
            else:
                return JsonResponse({'status': 'Failed', 'message': 'Maximum share limit reached '})
        except Cart.DoesNotExist:
            if project.max_shares_per_user > 0:
                if project.total_no_shares > 0:
                    chkCart = Cart.objects.create(user=request.user, project=project, quantity=1)
                    return JsonResponse({'status': 'Success', 'message': 'Added the project to the cart', 'cart_counter': get_cart_counter(request), 'qty': chkCart.quantity, 'cart_amount': get_cart_amounts(request)})
                else:
                    return JsonResponse({'status': 'Failed', 'message': 'No more shares available for this project!'})
            else:
                return JsonResponse({'status': 'Failed', 'message': 'Maximum share limit reached'})
    except Project.DoesNotExist:
        return JsonResponse({'status': 'Failed', 'message': 'This project does not exist!'})
    except ValidationError as e:
        error_message = ' '.join(e.messages)
        return JsonResponse({'status': 'Failed', 'message': error_message})
    
    
def decrease_cart(request, project_id):
    if request.user.is_authenticated:
        if request.headers.get('x-requested-with') == 'XMLHttpRequest':
            try:
                project = Project.objects.get(id=project_id)
                # Check if the user has already added that project to the cart
                try:
                    chkCart = Cart.objects.get(user=request.user, project=project)
                    if chkCart.quantity > 1:
                        # decrease the cart quantity
                        chkCart.quantity -= 1
                        chkCart.save()
                    else:
                        chkCart.delete()
                        chkCart.quantity = 0
                    return JsonResponse({'status': 'Success', 'cart_counter': get_cart_counter(request), 'qty': chkCart.quantity,'cart_amount': get_cart_amounts(request), })
                except:
                    return JsonResponse({'status': 'Failed', 'message': 'You do not have this item in your cart!'})
            except:
                return JsonResponse({'status': 'Failed', 'message': 'This food does not exist!'})
        else:
            return JsonResponse({'status': 'Failed', 'message': 'Invalid request!'})
        
    else:
        return JsonResponse({'status': 'login_required', 'message': 'Please login to continue'})



def delete_cart(request, cart_id):
    if request.user.is_authenticated:
        if request.headers.get('x-requested-with') == 'XMLHttpRequest':
            try:
                # Check if the cart item exists
                cart_item = Cart.objects.get(user=request.user, id=cart_id)
                if cart_item:
                    cart_item.delete()
                    return JsonResponse({'status': 'Success', 'message': 'Cart item has been deleted!', 'cart_counter': get_cart_counter(request),'cart_amount': get_cart_amounts(request)})

            except Cart.DoesNotExist:
                return JsonResponse({'status': 'Failed', 'message': 'Cart item does not exist!'})
        else:
            return JsonResponse({'status': 'Failed', 'message': 'Invalid request!'})
    else:
        return JsonResponse({'status': 'login_required', 'message': 'Please login to continue'})
    
    
@user_passes_test(check_role_customer)
@login_required(login_url = 'account:login')
def cart_view(request):
    
    cart_items = Cart.objects.filter(user=request.user).order_by('created_at')
    context = {
        'cart_items': cart_items,
    }
    return render(request, 'ecom/cart.html', context)



@user_passes_test(check_role_customer)
@login_required(login_url='account:login')
def checkout_view(request):
    
    cart_items = Cart.objects.filter(user=request.user).order_by('created_at')
    cart_count = cart_items.count()
    if cart_count <= 0:
        return redirect('ecom:shop')
    
    user_profile = UserProfile.objects.get(user=request.user)
    default_values = {
        'first_name': user_profile.first_name,
        'last_name': user_profile.last_name,
        'phone': request.user.phone_number,
        'email': user_profile.email,
        'address': user_profile.address,
        'country': user_profile.country,
        'state': user_profile.state,
        'city': user_profile.city,
        'pin_code': user_profile.pin_code,
    }

agritech/ecom/templates/ecom/cart.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
    

    

    <div class="ltn__utilize-overlay"></div>

    

    <!-- SHOPING CART AREA START -->
    <div class="liton__shoping-cart-area mb-120 mt-80">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="shoping-cart-inner">
                        <div class="shoping-cart-table table-responsive">
                            <table class="table">
                                {% comment %} <thead>
                                    <th class="cart-product-remove">Remove</th>
                                    <th class="cart-product-image">Image</th>
                                    <th class="cart-product-info">Product</th>
                                    <th class="cart-product-price">Price</th>
                                    <th class="cart-product-quantity">Quantity</th>
                                    <th class="cart-product-subtotal">Subtotal</th>
                                </thead>   {% endcomment %}
                                <tbody>
                                    {% if cart_items %}
                                    {% for cart_item in cart_items %}
                                    <tr  id="cart-item-{{ cart_item.id }}" >
                                        <td>
                                            <a href="#" class="delete_cart" data-id="{{ cart_item.id }}" data-url="{% url 'ecom:delete_cart' cart_item.id %}">
                                                <img src="{% static 'ecom/img/delete.png' %}">
                                            </a>
                                        </td>
                                        
                                        
                                        <td class="cart-product-image">
                                            <a href="{% url 'ecom:product' id=cart_item.project.id %}"><img src="{{ cart_item.project.farm_image.url }}" alt="#"></a>
                                        </td>
                                        <td class="cart-product-info">
                                            <h4><a href="{% url 'ecom:product' id=cart_item.project.id %}">{{ cart_item.project.project_title }}</a></h4>
                                        </td>
                                        <td class="cart-product-price">रु‎{{ cart_item.project.value_of_share|floatformat:2 }}</td>
                                        <td class="cart-product-quantity">
                                            <a href="#" class="decrease_cart" data-id="{{ cart_item.project.id }}" data-url="{% url 'ecom:decrease_cart' cart_item.project.id %}" onclick="decreaseCart(event, '{{ cart_item.project.id }}', '{% url "ecom:decrease_cart" cart_item.project.id %}')}" style="margin-right: 10px;">
                                                <img src="{% static 'ecom/img/minus.png' %}">
                                            </a>
                                            <label id="qty-{{ cart_item.project.id }}">{{ cart_item.quantity }}</label>
                                
                                            <a href="#" class="add_to_cart" data-id="{{ cart_item.project.id }}" data-url="{% url 'ecom:add_to_cart' cart_item.project.id %}" onclick="addToCart(event, '{{ cart_item.project.id }}', '{% url "ecom:add_to_cart" cart_item.project.id %}')}" style="margin-left: 10px;">
                                                <img src="{% static 'ecom/img/plus.png' %}">
                                            </a>
                                            
                                        </td>
                                        
                                        {% comment %} <td class="cart-product-subtotal">
                                            रु‎ 1000
                                        </td> {% endcomment %}
                                    </tr>
                                    {% endfor %} 
                                    {% else %}
    <div class="empty-cart-message">
        <h3>Cart Is Empty</h3>
    </div>
{% endif %}

<style>
    .empty-cart-message {
        display: flex;
        justify-content: center;
        align-items: center;
        height: 300px;
        width: 50%;
        margin: 0 auto;
        
        text-align: center;
    }

    .empty-cart-message h3 {
        font-size: 100px;
        color: #357960;
    }
</style>

                                    
                                    
                                </tbody>
                            </table>
                        </div>
                        <div class="shoping-cart-total mt-50">
                            <h4>Cart Totals</h4>
                            <table class="table">
                                <tbody>
                                    
                                    {% for key, value in tax_dict.items %}
                                        {% for i, j in value.items %}
                                            <tr>
                                                <td>{{ key }} <small>({{ i }}%)</small></td>
                                                <td>
                                                    <span class="price ">
                                                        <span class="currency">रु‎</span>
                                                        <span id="tax-{{ key }}">{{ j }}</span>
                                                    </span>
                                                </td>
                                            </tr>
                                        {% endfor %}
                                    {% endfor %}
                                    <tr>
                                        <td>Cart Subtotal</td>
                                        <td><span id="subtotal">रु‎ {{ subtotal }}</span></td>
                                    </tr>
                                    
                                    <tr>
                                        <td><strong>Order Total</strong></td>
                                        <td><strong>रु‎ <span id="total">{{ grand_total }}</span></strong></td>
                                    </tr>
                                </tbody>
                            </table>
                            <div class="btn-wrapper text-right">
                                <a href="{% url 'ecom:checkout' %}" class="theme-btn-1 btn btn-effect-1">Proceed to checkout</a>
                            </div>
                        </div>
                        
                        
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- SHOPING CART AREA END -->

   
   
</div>
{% endblock content %}

agritech/ecom/templates/ecom/checkout.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
 


    <!-- WISHLIST AREA START -->
    <div class="ltn__checkout-area mb-105 mt-40">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="ltn__checkout-inner">
                        <div class="ltn__checkout-single-content mt-50">
                            <h4 class="title-2">Billing Details</h4>   
                            <div class="ltn__checkout-single-content-info">
                                <form action="{% url 'place_order' %}" method="POST">
                                    {% csrf_token %}
                                    <h6>Personal Information</h6>
                                    <div class="row">
                                        <div class="form-group col-md-6 col-sm-12 col-lg-6">
                                            First Name: {{ form.first_name }}
                                        </div>
                                        <div class="form-group col-md-6 col-sm-12 col-lg-6">
                                            Last Name: {{ form.last_name }}
                                        </div>
                                    </div>

                                    <div class="row">
                                        <div class="form-group col-md-6 col-sm-12 col-lg-6">
                                            Phone Number: {{ form.phone }}
                                        </div>
                                        <div class="form-group col-md-6 col-sm-12 col-lg-6">
                                            Email Address: {{ form.email }}
                                        </div>
                                    </div>

                                    <div class="row">
                                        <div class="form-group col-md-12 col-sm-12 col-lg-12">
                                            Address: {{ form.address }}
                                        </div>
                                    </div>

                                    <div class="row">
                                        <div class="form-group col-md-6 col-sm-12 col-lg-6">
                                            Country: {{ form.country }}
                                        </div>
                                        <div class="form-group col-md-6 col-sm-12 col-lg-6">
                                            State: {{ form.state }}
                                        </div>
                                    </div>

                                    <div class="row">
                                        <div class="form-group col-md-6 col-sm-12 col-lg-6">
                                            City: {{ form.city }}
                                        </div>
                                        <div class="form-group col-md-6 col-sm-12 col-lg-6">
                                            Pin Code: {{ form.pin_code }}
                                        </div>
                                    </div>
                                
                            </div>
                        </div>

                    <div class="col-lg-12">
                    <div class="ltn__checkout-inner">
                        <div class="ltn__checkout-single-content mt-50">
                            <h4 class="title-2">Products</h4>   
                            <div class="ltn__checkout-single-content-info">
                            <table class="table" style="background-color:white;">
                                
                                <tbody>
                                    
                                    {% for cart_item in cart_items %}
                                    <tr  id="cart-item-{{ cart_item.id }}" >
                                        
                                        
                                        
                                        <td class="cart-product-image">
                                            <a href="product-details.html"><img src="{{ cart_item.project.farm_image.url }}" alt="#"></a>
                                        </td>
                                        <td class="cart-product-info">
                                            <h4><a href="product-details.html">{{ cart_item.project.project_title }}</a></h4>
                                        </td>
                                        <td class="cart-product-price">Rs{{ cart_item.project.value_of_share|floatformat:2 }}</td>
                                        <td class="cart-product-quantity">
                                            
                                            <label id="qty-{{ cart_item.project.id }}">{{ cart_item.quantity }}</label>
                                        </td>
                                        {% endfor %} 
                                    </tr>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
                            
        </div>
    </div>

        
                <div class="col-lg-6">
                    <div class="ltn__checkout-payment-method mt-50">
                        <h4 class="title-2">Payment Method</h4>
                        <div id="checkout_accordion_1">
                           
                            &emsp;
                            <label>
                                <input type="radio" name="payment_method" value="Khalti">
                                <img src="{% static 'ecom/img/icons/paymenta.png' %}" alt="Khalti" width="100">
                            </label>
                        </div>
                        <div class="ltn__payment-note mt-30 mb-30">
                            <p>Your personal data will be used to process your order, support your experience throughout this website, and for other purposes described in our privacy policy.</p>
                        </div>
                        <span class="text-danger" id="payment-method-error"></span><br>
                        <button onclick="return payMethodConfirm();" type="submit" class="btn theme-btn-1 btn-effect-1 text-uppercase" type="submit">Place order</button>
                    </div>
                </div>
            </form>
            <!-- form ends here -->
                <div class="col-lg-6">
                    <div class="shoping-cart-total mt-50">
                        <h4 class="title-2">Cart Totals</h4>
                        <table class="table">
                            <tbody>

                                {% for key, value in tax_dict.items %}
                                {% for i, j in value.items %}
                                    <tr>
                                        <td>{{ key }} <small>({{ i }}%)</small></td>
                                        <td>
                                            <span class="price ">
                                                <span class="currency">रु‎</span>
                                                <span id="tax-{{ key }}">{{ j }}</span>
                                            </span>
                                        </td>
                                    </tr>
                                {% endfor %}
                            {% endfor %}

                            {% for cart_item in cart_items %}
                            <tr>
                                <td>Quantity</td>
                                <td><span id="quantity"> {{ cart_item.quantity}} </span></td>
                            </tr>
                            <tr>
                         {% endfor %}

                                <td>Cart Subtotal</td>
                                <td><span id="subtotal">रु‎ {{ subtotal }}</span></td>
                            </tr>
                            
                            <tr>
                                <td><strong>Order Total</strong></td>
                                <td><strong>रु‎ <span id="total">{{ grand_total }}</span></strong></td>
                            </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- END -->
    <script>
        function payMethodConfirm(){
            var payMethod = $("input[name='payment_method']:checked").val()
            if(!payMethod){
                $('#payment-method-error').html("Select Payment Method!");
                return false;
            }else{
                var conf = confirm('You have selected '+payMethod+' as your preferred payment method.\nClick "OK" to continue.')
                if(conf == true){
                    return true;
                }else{
                    return false;
                }
            }
            
        }
    
        $('input[name=payment_method]').on('change', function(){
            $('#payment-method-error').html("");
        })
    </script>
    {% endblock content %}

agritech/ecom/templates/ecom/project_notification.html
Notification Page 