agritech/account/urls.py
from django.urls import path, include
from . import views

app_name ='account'
from .views import UserRegistrationView, OTPVerificationView
urlpatterns =[
    path('',views.myAccount),
    path('vendor-detail/<int:vendor_id>/', views.vendor_detail, name='vendor_detail'),

    path('register/', UserRegistrationView.as_view(), name='user_registration'),
    path('verify-otp/', OTPVerificationView.as_view(), name='otp_verification'),
    

    path('login/', views.login, name='login'),
    path('logout/',views.logout, name='logout'),
    path('myAccount/',views.myAccount, name='myAccount'),
    

    path('custdashboard/',views.custdashboard, name='custdashboard'),
    path('vendordashboard/',views.vendordashboard, name='vendordashboard'),
    path('customer_change_password/', views.customer_change_password, name='customer_change_password'),
    path('vendor_change_password/', views.vendor_change_password, name='vendor_change_password'),

    
    path('forgot_password/', views.forgot_password, name='forgot_password'),
    path('reset_password_validate/<uidb64>/<token>/', views.reset_password_validate, name='reset_password_validate'),
    path('reset_password/', views.reset_password, name='reset_password'),
    
    path('vendor/', include('vendor.urls')),
    path('customer/', include('customers.urls')),
    path('order/', include('orders.urls')),

]

agritech/agritech/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views 
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('ecom/',include('ecom.urls')),
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
    path('faq/', views.faq, name='faq'),
    path('agri-support/', views.agro_sup, name='blog'),
    path('contact/', views.contact, name='contact'),
    
    path('account/',include('account.urls')),
    # ORDERS
    path('orders/', include('orders.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

agritech/customers/urls.py
from django.urls import path
from account import views as AccountViews
from . import views


urlpatterns = [
    path('', AccountViews.custdashboard, name='customer'),
    path('profile/', views.cprofile, name='cprofile'),
    path('my_orders/', views.my_orders, name='customer_my_orders'),
    path('customer_order_detail/<int:order_number>/', views.order_detail, name='customer_order_detail'),
    path('my_investment/<int:customer_id>/projects/', views.my_investment, name='my_investment'),
    path('farm_status/<int:id>/', views.cfarm_status, name='cfarm_status'),
]

agritech/ecom/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static
 
app_name ='ecom'

urlpatterns =[
    path('' , views.shop_view,name='shop'),
    path('categories/<int:id>/', views.category_view, name='category-view'),
    path('<int:id>/', views.prod_view, name='product'),
     # ADD TO CART
    path('add_to_cart/<int:project_id>/', views.add_to_cart, name='add_to_cart'),
    # DECREASE CART
    path('decrease_cart/<int:project_id>/', views.decrease_cart, name='decrease_cart'),
    # DELETE CART ITEM
    path('delete_cart/<int:cart_id>/', views.delete_cart, name='delete_cart'),
    path('cart/', views.cart_view,name='cart'),
    
    path('checkout/', views.checkout_view,name='checkout')
   
]

agritech/templates/includes/alerts.html
{% if messages %}
    {% for message in messages %}
        <div class="alert alert-{{message.tags}} show-notification" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
           <strong>{{message}}</strong>
        </div>
    {% endfor %}
{% endif %}

agritech/templates/includes/c_sidebar.html
{% load static %}
<!-- ========== Left Sidebar Start ========== -->
<div class="vertical-menu" style="background-color:#E2F6CA;">

  <div data-simplebar class="h-100">

      <div class="navbar-brand-box">
          <a href="{% url 'index' %}" class="logo">
              <img src="{% static 'ecom/img/logo-2.png' %}">
              
          </a>
      </div>

      <!--- Sidemenu -->
      <div id="sidebar-menu">
          <!-- Left Menu Start -->
          <ul class="metismenu list-unstyled" id="side-menu">
            {% if user.is_verified %}
                <li >
                    <a href="{% url 'account:customer' %}" style="color: black;">
                        <i class="fas fa-home"></i> Dashboard
                    </a>
                </li>
                <li >
                    <a href="{% url 'account:customer_my_orders' %}" style="color: black;">
                        <i class="fas fa-shopping-cart"></i> My Orders
                    </a>
                </li>
                <li >
                    <a href="{% url 'account:my_investment' user.id %}" style="color: black;">
                        <i class="fas fa-briefcase"></i> My Investments
                    </a>
                </li>
            {% else %}
                <li >
                    <a href="{% url 'account:cprofile' %}" style="color: black;">
                        <i class="fas fa-user"></i> My Profile
                    </a>
                </li>
            {% endif %}
            <li>
                <a href="{% url 'account:customer_change_password' %}" style="color: black;">
                    <i class="fas fa-lock"></i> Security
                </a>
            </li>
            
          </ul>
      </div>
      <!-- Sidebar -->
  </div>
</div>
<!-- Left Sidebar End -->

agritech/templates/includes/cover.html
{% load static %}
<h1 class="text-center pt-10 pb-10 h-60"style="background: linear-gradient(to left, #E8A22B 0%,#fff 100%); margin-top:0px;">FARM STATUS</h1>

   

agritech/templates/includes/v_sidebar.html
{% load static %}
<!-- ========== Left Sidebar Start ========== -->
<div class="vertical-menu" style="background-color: #ffffff">
  <div data-simplebar class="h-100">
    <div class="navbar-brand-box">
      <a href="{% url 'index' %}" class="logo">
        <img src="{% static 'ecom/img/logo-2.png' %}" />
      </a>
    </div>

    <!--- Sidemenu -->
    <div id="sidebar-menu">
      <!-- Left Menu Start -->
      <ul class="metismenu list-unstyled" id="side-menu">
        <li>
          <a
            href="{% url 'account:vendordashboard' %}"
            style="color: black; font-weight: bold"
          >
            <i class="fas fa-home"></i> Dashboard
          </a>
        </li>
        {% if user.is_verified %}
        <li>
          <a
            href="{% url 'account:vprofile' %}"
            style="color: black; font-weight: bold"
          >
            <i class="fas fa-user"></i> My Profile
          </a>
        </li>
        <li>
          <a
            href="{% url 'account:menu_builder' %}"
            style="color: black; font-weight: bold"
          >
            <i class="fas fa-plus"></i> Projects
          </a>
        </li>
        <li>
          <a
            href="{% url 'account:vendor_my_orders' %}"
            style="color: black; font-weight: bold"
          >
            <i class="fas fa-file-invoice"></i> Order
          </a>
        </li>

        <li>
          <a
            href="{% url 'account:active farms' %}"
            style="color: black; font-weight: bold"
          >
            <i
              class="fas fa-circle"
              style="
                color: #5ad539;
                font-size: 8px;
                position: relative;
                top: -3px;
              "
            ></i>
            Active Farm
          </a>
        </li>
        <li>
          <a
            href="{% url 'account:vendor_detail' user.id %}"
            style="color: black; font-weight: bold"
          >
            <i class="fas fa-user"></i> My Details
          </a>
        </li>
        {% else %}
        <li>
          <a
            href="{% url 'account:vprofile' %}"
            style="color: black; font-weight: bold"
          >
            <i class="fas fa-user"></i> My Profile
          </a>
        </li>
        {% endif %}
        <li>
          <a
            href="{% url 'account:vendor_change_password' %}"
            style="color: black; font-weight: bold"
          >
            <i class="fas fa-lock"></i> Security
          </a>
        </li>
      </ul>
    </div>
    <!-- Sidebar -->
  </div>
</div>
<!-- Left Sidebar End -->